name: panc-codex-shiny
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas>=2.2
  - numpy>=1.26
  - openpyxl>=3.1
  - pillow>=10.4
  - statsmodels>=0.14
  - requests>=2.32
  - pyyaml>=6.0
  - tifftools  # available on conda-forge
  - lxml
  - r-base>=4.3
  - r-shiny
  - r-shinyjs
  - r-readxl
  - r-dplyr
  - r-stringr
  - r-tidyr
  - r-ggplot2
  - r-plotly
  - r-broom
  - r-jsonlite
  - r-scales
