name: panc-codex-streamlit
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - streamlit>=1.36
  - pandas>=2.2
  - numpy>=1.26
  - plotly>=5.22
  - openpyxl>=3.1
  - pillow>=10.4
  - statsmodels>=0.14
  - requests>=2.32
  - pyyaml>=6.0
  - pip:
      # Keep minimal; add only if truly needed via pip
      - plotly-express>=0.4.1
